<a href="https://colab.research.google.com/github/Jisang-hwang93/NLP_Class/blob/master/12%20Latent%20Semantic%20Analysis%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic Modeling - Latent Semantic Analysis 실습**

## **1. 잠재 의미 분석(LSA)**

In [ ]:
doc_ls = ['바나나 사과 포도 포도 짜장면',
          '사과 포도',
          '포도 바나나',
          '짜장면 짬뽕 탕수육',
          '볶음밥 탕수육',
          '짜장면 짬뽕',
          '라면 스시',
          '스시 짜장면',
          '가츠동 스시 소바',
          '된장찌개 김치찌개 김치',
          '김치 된장 짜장면',          
          '비빔밥 김치'
          ]

In [ ]:
# 각 문장 토큰화
docs = []
tokens = []

for i in range(len(doc_ls)):
    docs.append(doc_ls[i].split(" "))
    # 단어 뭉치 생성
    for word in docs[i]:
        tokens.append(word)
tokens = list(set(tokens))

docs, tokens

([['바나나', '사과', '포도', '포도', '짜장면'],
  ['사과', '포도'],
  ['포도', '바나나'],
  ['짜장면', '짬뽕', '탕수육'],
  ['볶음밥', '탕수육'],
  ['짜장면', '짬뽕'],
  ['라면', '스시'],
  ['스시', '짜장면'],
  ['가츠동', '스시', '소바'],
  ['된장찌개', '김치찌개', '김치'],
  ['김치', '된장', '짜장면'],
  ['비빔밥', '김치']],
 ['가츠동',
  '된장찌개',
  '된장',
  '라면',
  '김치찌개',
  '짬뽕',
  '비빔밥',
  '짜장면',
  '소바',
  '포도',
  '사과',
  '스시',
  '탕수육',
  '볶음밥',
  '김치',
  '바나나'])

In [ ]:
import pandas as pd

# TDM(문서-단어 행렬) 생성
TDM_matrix = []

for i in range(len(docs)):
    words_count = [0 for a in range(len(tokens))]
    for j in range(len(tokens)):
        if tokens[j] in docs[i]:
            words_count[j] += docs[i].count(tokens[j])
    TDM_matrix.append(words_count)

df = pd.DataFrame(TDM_matrix, index=doc_ls,  columns=tokens)
df

가츠동  된장찌개  된장  라면  김치찌개  짬뽕  ...  사과  스시  탕수육  볶음밥  김치  바나나
바나나 사과 포도 포도 짜장면    0     0   0   0     0   0  ...   1   0    0    0   0    1
사과 포도               0     0   0   0     0   0  ...   1   0    0    0   0    0
포도 바나나              0     0   0   0     0   0  ...   0   0    0    0   0    1
짜장면 짬뽕 탕수육          0     0   0   0     0   1  ...   0   0    1    0   0    0
볶음밥 탕수육             0     0   0   0     0   0  ...   0   0    1    1   0    0
짜장면 짬뽕              0     0   0   0     0   1  ...   0   0    0    0   0    0
라면 스시               0     0   0   1     0   0  ...   0   1    0    0   0    0
스시 짜장면              0     0   0   0     0   0  ...   0   1    0    0   0    0
가츠동 스시 소바           1     0   0   0     0   0  ...   0   1    0    0   0    0
된장찌개 김치찌개 김치        0     1   0   0     1   0  ...   0   0    0    0   1    0
김치 된장 짜장면           0     0   1   0     0   0  ...   0   0    0    0   1    0
비빔밥 김치              0     0   0   0     0   0  ...   0   0    0    0   1    0

[12 rows x 16 columns]

In [ ]:
import numpy as np

# 특이값 분해(SVD, Singular Value Decomposition)
U, s, VT = np.linalg.svd(TDM_matrix)

print("U:\n {}".format(U))
print("s:\n {}".format(s))
print("VT:\n {}".format(VT))

U:
 [[ 7.99091783e-01 -2.36316994e-01 -1.00528910e-02 -1.86641353e-02
   2.26958130e-02 -1.49376350e-03 -2.77279457e-03 -3.68544915e-02
  -8.66705696e-18  1.17652823e-01  2.96599016e-02  5.37170383e-01]
 [ 3.24228913e-01 -2.37554400e-01 -2.30122874e-02 -5.61972271e-02
  -9.68984211e-02  3.15314058e-03  5.42121261e-03  5.97770914e-02
  -7.07106781e-01 -1.44987002e-01 -3.17878330e-02 -5.47468895e-01]
 [ 3.24228913e-01 -2.37554400e-01 -2.30122874e-02 -5.61972271e-02
  -9.68984211e-02  3.15314058e-03  5.42121261e-03  5.97770914e-02
   7.07106781e-01 -1.44987002e-01 -3.17878330e-02 -5.47468895e-01]
 [ 2.12081980e-01  4.85658930e-01  1.28131746e-01  4.30050644e-01
  -2.29550714e-01 -1.49219512e-01  7.74475499e-02  2.17717819e-01
  -3.01147995e-15 -1.91835325e-01 -5.93643666e-01  1.49190202e-02]
 [ 2.52665818e-02  1.21890924e-01  5.54551687e-02  2.15417887e-01
  -7.72035525e-01  3.54259781e-01 -1.44920552e-01 -2.56260382e-01
   6.68909372e-15  1.33737715e-01  3.29953280e-01 -7.67610447e-03]
 

In [ ]:
# 주제 개수 설정
k = 4

# 주제-단어 행렬
VT_matrix = VT.T[:, :k]
columns_name = ["Topic {}".format(i+1) for i in range(k)]
df = pd.DataFrame(VT_matrix, index=tokens, columns=columns_name)
print(VT_matrix)
# 단어 순위 설정
word_num = 3

# 순위 출력 결과
topic_result = []
for name in columns_name:
    topic_top = df[name].sort_values(ascending=False)[0:word_num]
    topic_result.append(([topic_top.index, topic_top.values]))

topic_result

[[ 0.0082077   0.06425309  0.22621639 -0.27669846]
 [ 0.00922069  0.0845808  -0.26439785 -0.1860217 ]
 [ 0.0599366   0.18480907 -0.16197315 -0.06140467]
 [ 0.00733397  0.05136218  0.15788435 -0.18435345]
 [ 0.00922069  0.0845808  -0.26439785 -0.1860217 ]
 [ 0.12448389  0.3555557   0.10291629  0.34945274]
 [ 0.00823912  0.06761161 -0.18453253 -0.12393905]
 [ 0.48563449  0.58415588  0.07468389  0.18737521]
 [ 0.0082077   0.06425309  0.22621639 -0.27669846]
 [ 0.69686254 -0.38741921 -0.03185185 -0.07489549]
 [ 0.34843127 -0.19370961 -0.01592593 -0.03744775]
 [ 0.06889362  0.25600828  0.52268348 -0.55238845]
 [ 0.0736207   0.24835482  0.0884251   0.3228814 ]
 [ 0.00783718  0.04982669  0.02671012  0.10775805]
 [ 0.07739641  0.33700147 -0.61090353 -0.37136542]
 [ 0.34843127 -0.19370961 -0.01592593 -0.03744775]]


[[Index(['포도', '짜장면', '바나나'], dtype='object'),
  array([0.69686254, 0.48563449, 0.34843127])],
 [Index(['짜장면', '짬뽕', '김치'], dtype='object'),
  array([0.58415588, 0.3555557 , 0.33700147])],
 [Index(['스시', '가츠동', '소바'], dtype='object'),
  array([0.52268348, 0.22621639, 0.22621639])],
 [Index(['짬뽕', '탕수육', '짜장면'], dtype='object'),
  array([0.34945274, 0.3228814 , 0.18737521])]]

In [ ]:
# 최종 결과
result = []

for i in range(len(topic_result)):
    tmp_result = []
    for j in range(word_num):
        tmp_result.append((topic_result[i][0][j], topic_result[i][1][j]))
    result.append(tmp_result)

result

[[('포도', 0.6968625387988912),
  ('짜장면', 0.48563448882209054),
  ('바나나', 0.3484312693994456)],
 [('짜장면', 0.584155883785207),
  ('짬뽕', 0.35555569681876015),
  ('김치', 0.33700147191297797)],
 [('스시', 0.5226834790874939),
  ('가츠동', 0.22621638508821545),
  ('소바', 0.22621638508821543)],
 [('짬뽕', 0.34945273623176065),
  ('탕수육', 0.322881399504073),
  ('짜장면', 0.1873752139119877)]]

In [ ]:
for i in range(len(result)):
    print("{} - {}".format(columns_name[i], result[i]))

Topic 1 - [('포도', 0.6968625387988912), ('짜장면', 0.48563448882209054), ('바나나', 0.3484312693994456)]
Topic 2 - [('짜장면', 0.584155883785207), ('짬뽕', 0.35555569681876015), ('김치', 0.33700147191297797)]
Topic 3 - [('스시', 0.5226834790874939), ('가츠동', 0.22621638508821545), ('소바', 0.22621638508821543)]
Topic 4 - [('짬뽕', 0.34945273623176065), ('탕수육', 0.322881399504073), ('짜장면', 0.1873752139119877)]


## **2. LSA 클래스화**

In [ ]:
import pandas as pd
import numpy as np

class LSA():
    def __init__(self):
        self.docs = []
        self.tokens = []
        self.TDM_matrix = []
        self.U = []
        self.s = []
        self.VT = []
        
    # 각 문장 토큰화        
    def make_token(self, doc_ls):
        tmp = []
        for i in range(len(doc_ls)):
            self.docs.append(doc_ls[i].split(" "))
            # 단어 뭉치 생성
            for word in self.docs[i]:
                tmp.append(word)
        self.tokens = list(set(tmp))

        return self.docs, self.tokens

    # TDM(문서-단어 행렬) 생성
    def make_TDM(self):
        for i in range(len(self.docs)):
            words_count = [0 for a in range(len(self.tokens))]
            for j in range(len(self.tokens)):
                if self.tokens[j] in self.docs[i]:
                    words_count[j] += self.docs[i].count(self.tokens[j])
            self.TDM_matrix.append(words_count)

        return self.TDM_matrix

    # 특이값 분해(SVD, Singular Value Decomposition)
    def make_svd(self):
        self.U, self.s, self.VT = np.linalg.svd(self.TDM_matrix)

        return self.U, self.s, self.VT

    # 주제 단어 행렬
    def topic_word(self, k, word_num):
        VT_matrix = self.VT.T[:, :k]
        columns_name = ["Topic {}".format(i+1) for i in range(k)]
        df = pd.DataFrame(VT_matrix, index=self.tokens, columns=columns_name)

        # 순위 출력 결과
        topic_result = []
        for name in columns_name:
            topic_top = df[name].sort_values(ascending=False)[0:word_num]
            topic_result.append(([topic_top.index, topic_top.values]))

        # 최종 결과물
        result = []
        for i in range(len(topic_result)):
            tmp_result = []
            for j in range(word_num):
                tmp_result.append((topic_result[i][0][j], topic_result[i][1][j]))
            result.append(tmp_result)

        # 결과 출력
        for i in range(len(result)):
            print("{} - {}".format(columns_name[i], result[i]))

    # 자동 실행 함수
    def run(self, doc_ls, k, word_num):
        self.make_token(doc_ls)
        self.make_TDM()
        self.make_svd()
        self.topic_word(k, word_num)

In [ ]:
doc_ls = ['바나나 사과 포도 포도 짜장면',
          '사과 포도',
          '포도 바나나',
          '짜장면 짬뽕 탕수육',
          '볶음밥 탕수육',
          '짜장면 짬뽕',
          '라면 스시',
          '스시 짜장면',
          '가츠동 스시 소바',
          '된장찌개 김치찌개 김치',
          '김치 된장 짜장면',          
          '비빔밥 김치'
          ]

In [ ]:
lsa = LSA()

In [ ]:
print('== 토픽 모델링 ==')
lsa.run(doc_ls, 4, 3)

== 토픽 모델링 ==
Topic 1 - [('포도', 0.6968625387988912), ('짜장면', 0.48563448882209054), ('바나나', 0.3484312693994456)]
Topic 2 - [('짜장면', 0.584155883785207), ('짬뽕', 0.35555569681876015), ('김치', 0.33700147191297797)]
Topic 3 - [('스시', 0.5226834790874939), ('가츠동', 0.22621638508821545), ('소바', 0.22621638508821543)]
Topic 4 - [('짬뽕', 0.34945273623176065), ('탕수육', 0.322881399504073), ('짜장면', 0.1873752139119877)]
