<a href="https://colab.research.google.com/github/jisang93/NLP_Class/blob/master/16%20Deep%20Learning%20XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np

# X, Y 값
X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]])
Y = np.array([[0, 1, 1, 0]])

X, Y

(array([[0, 0, 1, 1],
        [0, 1, 0, 1]]), array([[0, 1, 1, 0]]))

In [34]:
# # X-히든 레이어 가중치
# h1 = np.random.rand(2, 2)
# h1_bias = np.random.rand(1, 2)

# # 히든 레이너-Y 가중치
# h2 = np.random.rand(2, 1)
# h2_bias = np.random.rand(1, 1)

# h1, h2, h1_bias, h2_bias
h1_weight = np.array([[-0.89, 0.028], [0.098, -0.07]])
h1_bias = np.array([[0.092], [-0.01]])

h2_weight = np.array([[0.056], [0.067]])
h2_bias = np.array([[0.016]])

In [35]:
# X*Weight + Bias*Weight
h1_cal = np.dot(h1_weight, X) + h1_bias

h1_cal

array([[ 0.092,  0.12 , -0.798, -0.77 ],
       [-0.01 , -0.08 ,  0.088,  0.018]])

In [36]:
# 시그모이드 함수
def sigmoid(x):
	return 1 / (1 + np.exp(-x))
 
h1_sig = sigmoid(h1_cal)
h1_sig

array([[0.52298379, 0.52996405, 0.3104535 , 0.31647911],
       [0.49750002, 0.48001066, 0.52198581, 0.50449988]])

In [37]:
h2_cal = np.dot(h1_sig.T, h2_weight) + h2_bias
h2_cal

array([[0.07861959],
       [0.0778387 ],
       [0.06835845],
       [0.06752432]])

In [38]:
predict = sigmoid(h2_cal)
predict

array([[0.51964478],
       [0.51944986],
       [0.51708296],
       [0.51687467]])

In [39]:
diff = Y.T - predict
diff

array([[-0.51964478],
       [ 0.48055014],
       [ 0.48291704],
       [-0.51687467]])

In [48]:
def loss(r, p):
   return -((np.dot(r, np.log(p)) + np.dot((1 - r), np.log(1-p)))/len(r[0]))[0][0]

L = loss(Y, predict)
L

0.6938113835190924

In [41]:
grad_h2 = np.dot(h1_sig, diff)

grad_h2

array([[-0.03074824],
       [-0.03654146]])

In [42]:
alpha = 0.01
h2_weight = h2_weight - grad_h2 * alpha
h2_weight

array([[0.05630748],
       [0.06736541]])

In [43]:
h2_bias = h2_bias - alpha * diff

In [44]:
h2_bias

array([[0.02119645],
       [0.0111945 ],
       [0.01117083],
       [0.02116875]])

In [45]:
 h1_weight = h1_weight - alpha * np.dot(X, np.dot(np.dot(np.dot(h2_weight, diff.T).T, h1_sig), (1 - h1_sig).T))
 h1_weight

array([[-0.88995553,  0.02803898],
       [ 0.09804757, -0.0699583 ]])

In [47]:
h1_bias = h1_bias - np.dot(np.dot(np.dot(h2_weight, diff.T).T, h1_sig), (1 - h1_sig).T).T
h1_bias

array([[ 0.16005832,  0.02906194,  0.02875195,  0.15969551],
       [ 0.04965765, -0.0651694 , -0.06544113,  0.04933963]])